### ISSUE TITLE
Netplay doesn't work out of the box

### ISSUE THREAD

**Issue by nachoverdon** [JLaferri/project-slippi#3]
Reason:
Memory cards/SD cards are disabled by default on Netplay.

Possible fixes:

 

- Change the default value of the checkbox that manages this option.
https://github.com/JLaferri/Ishiiruka/blob/upgrade/fm-5-9b-slippi/Source/Core/DolphinWX/NetPlay/NetWindow.cpp#L285
Add `m_memcard_write->SetValue(true);`
- Make it so that Dolphin ignores that option and loads Slippi no matter what.

**Comment by nachoverdon** [comment]
@JLaferri Wasn't this fixed already?

**Comment by rosshadden** [comment]
Forgive my ignorance, but does this issue mean "project-slippi doesn't work with other project-slippi users out of the box", or "project-slippi doesn't work with non-project-slipper users out of the box"?

That is, is Project Slippi expected to work when playing with people that have normal Faster Melee builds, or do all users need to be running it? I would have assumed the latter, but this issue made me want to ask, since there are two ways to interpret it.

**Comment by nachoverdon** [comment]
Memory cards need to be enabled in order to get Slippi working, but they are disabled by default, so it won't work unless you enable them manually, no matter what the other person is using. But again, I believe this issue was fixed a long ago.

**Comment by JLaferri** [comment]
Yeah sorry super late responding to this but it was fixed in the released builds. Gonna close issue.
